### ISSUE TITLE
Can you point to resourced used?

### ISSUE THREAD

**Issue by trsh** [holger-kibur/sdf#1]
Very interesting project. Will definitely fallow. Can you put the materials used in readme. I could not, for example, find anything on branch-and-prune knn tree ://

**Comment by holger-kibur** [comment]
[This](https://datalab-old.csd.auth.gr/~apostol/pubs/icdt97.pdf) is essentially the algorithm I am using. In this paper it is applied to R-trees, but the "pruning" part of the algorithm can be applied to any hierarchical data structure where the minimum and maximum leaf-node bounds are accessible in the parent e.g. anything with hierarchical bounding boxes. These are the MINDIST, MAXDIST, and MINMAXDIST values the algorithm refers to.

Some aspects of the tree itself are taken from [this paper](http://gamma.cs.unc.edu/SSV/obb.pdf).

The bounding box construction algorithms are novel. The idea is that the axes of the parent bounding box will be the eigen-vectors of the covariance matrix of all the child bounding-box vertex mean-deviations (vertex - vertex_mean). After finding these axes, you just find the max/min projections on all these axes from all the child bounding-box vertices, and from those you can construct a new parent bounding box. It is essentially a statistical technique.

I am still in the process of developing other aspects of the tree, but I will write some documentation once I have a working implementation.
